GetStream/stream-chat-php

composer.json
tests/integration/IntegrationTest.php
tests/unit/ClientTest.php

upgrade dependencies to latest versions

upgrade all packages to latest versions

---

lib/GetStream/StreamChat/Channel.php
lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

Add some methods and leave some unimplemented as they are not as relevant server-side

Fix some omissions

---

README.md
lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

deprecate client->getChannel (in favor of client->Channel)

deprecate client->getChannel (in favor of client->Channel)

---

lib/GetStream/StreamChat/Client.php

Add partial update

---

lib/GetStream/StreamChat/Channel.php
tests/integration/IntegrationTest.php

add queryMembers implementation

---

composer.json

Update guzzlehttp dependency to allow 7.0.1

Update guzzle version

---

.travis.yml
lib/GetStream/StreamChat/Channel.php
tests/integration/IntegrationTest.php

Fix member user id and support empty in query members

---

lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php
tests/unit/ClientTest.php

Fix location in client setup

---

lib/GetStream/StreamChat/Client.php

Fix phpdoc for devices

---

lib/GetStream/StreamChat/Channel.php
tests/integration/IntegrationTest.php

Add mute channel support

---

lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

Add support for message filters

---

lib/GetStream/StreamChat/Client.php

Use post for query channels

---

lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

This PR adds support for the GetRateLimits endpoint which returns the rate limits quota and usage.

add support for GetRateLimits

---

lib/GetStream/StreamChat/Client.php

Throw exp for empty filters of query channels

---

.github/workflows/ci.yml
.phan/config.php
composer.json

Composer v2 and Phan

---

.github/workflows/ci.yml
.gitignore
.php_cs.dist
composer.json
lib/GetStream/StreamChat/Channel.php
lib/GetStream/StreamChat/Client.php
lib/GetStream/StreamChat/StreamException.php
tests/integration/IntegrationTest.php
tests/unit/ClientTest.php

Add php cs fixer

---

lib/GetStream/StreamChat/Client.php

Version constant php7.4+

---

lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

Feature: Search improvements

---

lib/GetStream/StreamChat/Client.php

Fixed issuedAt typecheck

---

.gitignore
composer.json
lib/GetStream/StreamChat/Client.php
phpunit.xml.dist
tests/integration/IntegrationTest.php

This PR adds basic support for Permissions API and revamps some dev dependencies

Add Permissions API endpoints + dependency updates

---

lib/GetStream/StreamChat/Channel.php
lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

[CHAT-2191] Async delete_users

---

README.md
lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

deprecate updateUsers in favor upsertUsers

---

lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

[CHAT-2597] Add shadow_ban, remove_shadow_ban, update_message_partial, pin_message & unpin_message methods

---

.gitignore
lib/GetStream/StreamChat/Channel.php
tests/integration/IntegrationTest.php

Part of CHAT-2622
Note: this repo should require at least 1 reviewer. I can merge it myself which is not good.

feat: add truncate options

---

lib/GetStream/StreamChat/Channel.php
tests/integration/IntegrationTest.php

Add options to add members api

feat: add options to add members

---

lib/GetStream/StreamChat/Channel.php
lib/GetStream/StreamChat/Client.php
lib/GetStream/StreamChat/StreamRateLimit.php
lib/GetStream/StreamChat/StreamResponse.php
tests/integration/IntegrationTest.php

- Add rate limit to response body
Adding @madsroskar since he has some PHP experience.

feat: add ratelimit to response

---

lib/GetStream/StreamChat/Channel.php
tests/integration/IntegrationTest.php

fix: fix invitation and channel update logic

---

.github/workflows/initiate_release.yml

The tags in this repository dont have a v prefix

ci: tags dont have v prefix

---

.github/workflows/ci.yml
lib/GetStream/StreamChat/Channel.php
lib/GetStream/StreamChat/StreamRateLimit.php
lib/GetStream/StreamChat/StreamResponse.php
tests/integration/IntegrationTest.php

style: autoformat all files

---

lib/GetStream/StreamChat/Client.php
tests/integration/IntegrationTest.php

feat: add new moderation apis

---

lib/GetStream/StreamChat/Client.php

feat: add push providers

---

lib/GetStream/StreamChat/Client.php

feat: add device fields

---

README.md

add information about datetime serializing

docs: add information about datetime serializing

---

.github/workflows/ci.yml

ci: print test coverage

---

composer.json
lib/GetStream/StreamChat/Channel.php
lib/GetStream/StreamChat/Client.php

docs: add docs to public methods

docs: add docs to public methods

---

.phan/config.php
lib/GetStream/StreamChat/Channel.php
lib/GetStream/StreamChat/Client.php
lib/GetStream/StreamChat/StreamException.php
tests/integration/IntegrationTest.php

Bonus: stricter linter (phan) rules! Documentation is mandatory now.

feat(imports): add import endpoints

---

README.md

Fix undefined variable in reply message example

---

lib/GetStream/StreamChat/Channel.php
tests/integration/IntegrationTest.php

feat: add options to send message

---

lib/GetStream/StreamChat/Client.php

https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated

fix: deprecated string interpolation

---

lib/GetStream/StreamChat/Channel.php
tests/integration/IntegrationTest.php

https://getstream.slack.com/archives/C04SDJ3BC6Q/p1688484312536389

feat: added assignRoles endpoint

---

lib/GetStream/StreamChat/Channel.php

https://getstream.slack.com/archives/C04SDJ3BC6Q/p1711132290178849

[PBE-0] change user to user_id as part of payload
